### ISSUE TITLE
Build Failing Compiling GooglePlusShare.o when using RNShare.podspec

### ISSUE THREAD

**Issue by onlinegeek101** [EstebanFuentealba/react-native-share#100]
I am trying to use the defined podspec to setup my xcode dependencies but I am getting an issue w/ the GooglePlusShare files. Does this pod for you as is?

Failure
```
The following build commands failed:
	CompileC /<Actual Build Path>/ios/build/Build/Intermediates/RNShare.build/Debug-iphonesimulator/RNShare.build/Objects-normal/x86_64/GooglePlusShare.o GooglePlusShare.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

Pod declarations. (React is being pulled in locally as the cocoapods.org podspec is deprecated)
```
  pod 'React', :path => '../node_modules/react-native',
    :subspecs => [
      'Core',
      'RCTPushNotification',
      'RCTLinkingIOS'
    ]
  pod 'RNShare', :path => '../node_modules/react-native-share'
```

**Comment by dwilt** [comment]
@onlinegeek101 are you trying to build with React Native version `0.40.0`?

**Comment by onlinegeek101** [comment]
Nope 0.39.2

**Comment by dwilt** [comment]
Ok, well I noticed that there have been some significant upgrades to the core files in the past few versions. I'm upgrading from `0.37.0` to `0.40.0` and getting this error: 

`'React/RCTConvert.h' file not found`

![image](https://cloud.githubusercontent.com/assets/1065539/22083244/fed58ba0-dd7f-11e6-8e9a-104b9b6b3ddc.png)

**Comment by onlinegeek101** [comment]
Wanna drop your podfile as well just so we have clarity?

**Comment by dwilt** [comment]
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

workspace 'GreatJonesStreet.xcworkspace'
project 'GreatJonesStreet.xcodeproj'

target 'GreatJonesStreet' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GreatJonesStreet
  pod 'OneSignal', '~> 1.13.2'
  pod 'Branch'
  pod 'Mixpanel'

  target 'GreatJonesStreetTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by onlinegeek101** [comment]
Even more interesting I thought mine might be caused by me doing the react pod stuff.

```
pod 'React', :path => '../node_modules/react-native',
    :subspecs => [
      'Core',
      'RCTPushNotification',
      'RCTLinkingIOS'
    ]
```

But that doesn't seem to be the case

**Comment by EstebanFuentealba** [comment]
npm install react-native-share@1.0.17 --save

??

**Comment by steveliles** [comment]
Unfortunately 1.0.18 introduces a breaking change by referring to the new location of native headers that were moved in react-native 0.40.0. This means 1.0.18 is only compatible with react-native 0.40+. 

We hit the same problem yesterday because our package.json contained:

```
"react-native-share": "^1.0.16"
```

... so npm automatically upgraded a fresh npm-install to 1.0.18.

Probably 1.0.18 should have been a major version bump to 2.0.0 as recommended in the react-native [release notes for 0.40.0](https://github.com/facebook/react-native/releases/tag/v0.40.0)?

**Comment by dwilt** [comment]
@steveliles were you able to get this plugin working on `0.40.0`?

**Comment by steveliles** [comment]
@dwilt no we're on 0.34.1 - didn't try to upgrade yet due to other native dependencies that aren't updated to 0.40.0 compatibility.

Your issue looks like the opposite to ours - that you _want_ to use 1.0.18 for its RN-0.40.0 compatibility, but for some reason your xcode project doesn't have the RN-0.40.0 headers ...
