### ISSUE TITLE
onClose - Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by andyfenelon** [EstebanFuentealba/react-native-share#42]
> 2016-08-01 11:09:59.584 [warn][tid:com.facebook.react.JavaScript] Possible Unhandled Promise Rejection (id: 3):

getting this error on pressing close running the example

**Comment by IsTheJack** [comment]
I was getting this error too: 
![simulator screen shot aug 1 2016 2 35 32 pm](https://cloud.githubusercontent.com/assets/7907666/17304582/b46f0220-57fc-11e6-9e44-a42b592ca2ac.png)

**Comment by markgoodyear** [comment]
I'm getting this also.

**Comment by markgoodyear** [comment]
@andyfenelon, @IsTheJack, Actually, this is solved by just adding in a `catch`. If a user doesn't share, it throws an error of `Object {error: "User did not share"}` — which will be unhandled without a catch.

So to prevent the warning you can do:

```
Share.open({
  // share config here
})
.catch(err => console.log(err));
```

**Comment by ncuillery** [comment]
I don't really like this workaround. IMO the module shouldn't reject the promise in this case because it's not an "error scenario".

At least, the rejected value must allow distinction between this case and real errors (creating a `UserCancelError` should do the job).

According to the JS coding conventions, a promise should reject a instance of Error (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/reject#Description), not an object containing a key named `error`

I'd remove the use of `Exception` that is not standard in JavaScript: https://github.com/EstebanFuentealba/react-native-share/blob/master/index.js#L71 (or maybe it's a Windows thing ?)

Are you guys open to a PR ?
